(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(column-number-mode t)
 '(company-dabbrev-downcase nil)
 '(create-lockfiles nil)
 '(custom-safe-themes
   '("a27c00821ccfd5a78b01e4f35dc056706dd9ede09a8b90c6955ae6a390eb1c1e" default))
 '(dabbrev-case-fold-search nil)
 '(datetime-timezone 'Etc/GMT+8)
 '(dired-listing-switches "-alh")
 '(ffap-machine-p-known 'reject)
 '(flycheck-disabled-checkers '(json-python-json))
 '(flycheck-standard-error-navigation nil)
 '(flyspell-duplicate-distance 0)
 '(flyspell-mark-duplications-flag nil)
 '(helm-ag-insert-at-point 'symbol)
 '(helm-buffer-max-length 50)
 '(helm-split-window-default-side 'other)
 '(imenu-max-item-length nil)
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(ispell-dictionary "american")
 '(ispell-extra-args '("--camel-case"))
 '(ispell-program-name "aspell")
 '(lsp-completion-show-detail nil)
 '(lsp-eldoc-enable-hover nil)
 '(lsp-enable-indentation nil)
 '(lsp-enable-on-type-formatting nil)
 '(lsp-enable-symbol-highlighting nil)
 '(lsp-file-watch-threshold 100000)
 '(lsp-headerline-breadcrumb-enable nil)
 '(lsp-java-completion-filtered-types ["java.awt.*" "com.sun.*" "java.lang.StrictMath"])
 '(lsp-java-completion-guess-method-arguments nil)
 '(lsp-java-completion-max-results 10)
 '(lsp-java-format-enabled nil)
 '(lsp-java-format-on-type-enabled nil)
 '(lsp-java-vmargs
   '("-noverify" "-Xmx2G" "-XX:+UseG1GC" "-XX:+UseStringDeduplication" "-javaagent:/Users/zjq/opt/lombok.jar"))
 '(lsp-lens-enable nil)
 '(lsp-modeline-code-actions-enable nil)
 '(lsp-modeline-diagnostics-enable nil)
 '(lsp-signature-auto-activate nil)
 '(lsp-signature-render-documentation nil)
 '(lsp-ui-doc-enable nil)
 '(lsp-ui-doc-include-signature t)
 '(lsp-ui-doc-max-height 30)
 '(lsp-ui-doc-use-webkit t)
 '(lsp-ui-sideline-enable nil)
 '(magit-diff-refine-hunk 'all)
 '(make-backup-files nil)
 '(markdown-command "multimarkdown")
 '(markdown-fontify-code-block-default-mode 'ignore)
 '(markdown-fontify-code-blocks-natively t)
 '(nxml-child-indent 4)
 '(package-archive-priorities '(("melpa" . 1)))
 '(package-selected-packages
   '(yaml-pro highlight-indentation dockerfile-mode markdown-mode lsp-mode highlight-parentheses yaml-mode json-mode dap-mode lsp-java lsp-ui company-lsp hydra helm-projectile projectile helm-ag helm doom-modeline all-the-icons ztree multiple-cursors ace-window magit yasnippet symbol-overlay flycheck company expand-region))
 '(projectile-project-root-files
   '("build.sbt" "build.gradle" "pom.xml" "requirements.txt" "package.json" "Makefile" "Chart.yaml"))
 '(scroll-bar-mode nil)
 '(scroll-error-top-bottom t)
 '(tool-bar-mode nil)
 '(use-package-always-ensure t))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :extend nil :stipple nil :background "white" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "nil" :family "Monaco"))))
 '(flyspell-duplicate ((t (:underline "#ececec"))))
 '(flyspell-incorrect ((t (:underline "#ececec"))))
 '(line-number ((t (:inherit (shadow default) :background "ivory" :foreground "gray92"))))
 '(lsp-face-highlight-read ((t (:background "#e5e5e5"))))
 '(lsp-face-highlight-write ((t (:background "#e5e5e5" :weight bold))))
 '(lsp-ui-peek-filename ((t (:foreground "blue"))))
 '(lsp-ui-peek-header ((t (:background "ivory4" :foreground "white"))))
 '(lsp-ui-peek-highlight ((t (:underline "gray70"))))
 '(lsp-ui-peek-line-number ((t (:foreground "grey80"))))
 '(lsp-ui-peek-list ((t (:background "ivory1"))))
 '(lsp-ui-peek-peek ((t (:background "ivory1"))))
 '(lsp-ui-peek-selection ((t (:weight bold))))
 '(magit-diff-added ((t (:extend t :foreground "#22aa22"))))
 '(magit-diff-added-highlight ((t (:extend t :foreground "#22aa22"))))
 '(magit-diff-removed ((t (:extend t :foreground "#aa2222"))))
 '(magit-diff-removed-highlight ((t (:extend t :foreground "#aa2222"))))
 '(markdown-inline-code-face ((t (:inherit (markdown-code-face font-lock-constant-face) :background "#F5F8FA" :foreground "#657786"))))
 '(markdown-link-face ((t nil))))
