(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(cape-dabbrev-min-length 1)
 '(column-number-mode t)
 '(corfu-auto t)
 '(create-lockfiles nil)
 '(dabbrev-case-fold-search nil)
 '(datetime-timezone 'Etc/GMT+8)
 '(dired-listing-switches "-alh")
 '(eglot-events-buffer-size 0)
 '(eglot-report-progress nil)
 '(embark-mixed-indicator-delay 1.5)
 '(enable-recursive-minibuffers t)
 '(ffap-machine-p-known 'reject)
 '(fill-column 100)
 '(imenu-max-item-length 100)
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(initial-major-mode 'text-mode)
 '(ispell-dictionary "american")
 '(ispell-extra-args '("--camel-case"))
 '(ispell-program-name "aspell")
 '(js-jsx-syntax t)
 '(magit-diff-highlight-hunk-body nil)
 '(magit-diff-refine-hunk 'all)
 '(magit-save-repository-buffers 'dontask)
 '(make-backup-files nil)
 '(markdown-asymmetric-header t)
 '(markdown-command "multimarkdown")
 '(markdown-display-remote-images t)
 '(markdown-fontify-code-blocks-natively t)
 '(markdown-max-image-size '(500 . 500))
 '(nxml-child-indent 4)
 '(orderless-matching-styles '(orderless-regexp orderless-literal orderless-initialism))
 '(package-archive-priorities '(("melpa" . 1)))
 '(package-native-compile t)
 '(package-selected-packages
   '(edit-indirect nginx-mode polymode groovy-mode git-timemachine jinja2-mode flymake-collection docker yaml-pro vundo doom-themes cape corfu wgrep vertico orderless embark-consult marginalia markdown-mode doom-modeline ztree multiple-cursors ace-window magit yasnippet symbol-overlay expand-region))
 '(project-vc-extra-root-markers '("Chart.yaml"))
 '(scroll-bar-mode nil)
 '(scroll-error-top-bottom t)
 '(symbol-overlay-priority 100)
 '(tool-bar-mode nil)
 '(xref-history-storage 'xref-window-local-history)
 '(yaml-pro-ts-yank-subtrees nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(avy-lead-face ((t (:background "#282c34" :foreground "green" :weight bold))))
 '(aw-leading-char-face ((t (:foreground "green" :weight bold))))
 '(corfu-current ((t (:background "#42444a" :foreground "#bbc2cf"))))
 '(eglot-highlight-symbol-face ((t (:foreground "red" :weight bold))))
 '(flyspell-duplicate ((t (:underline nil))))
 '(font-lock-comment-face ((t (:foreground "dark cyan"))))
 '(font-lock-function-call-face ((t (:foreground "#bbc2cf"))))
 '(font-lock-string-face ((t (:foreground "#5B6268"))))
 '(font-lock-type-face ((t (:foreground "#5B6268"))))
 '(font-lock-variable-name-face ((t (:foreground "#bbc2cf"))))
 '(sh-quoted-exec ((t (:foreground "#5B6268"))))
 '(symbol-overlay-face-1 ((t (:background "wheat1" :foreground "#282c34"))))
 '(symbol-overlay-face-2 ((t (:background "tan1" :foreground "#282c34"))))
 '(symbol-overlay-face-3 ((t (:background "yellow1" :foreground "#282c34"))))
 '(symbol-overlay-face-4 ((t (:background "chartreuse1" :foreground "#282c34"))))
 '(symbol-overlay-face-5 ((t (:background "DarkSeaGreen1" :foreground "#282c34"))))
 '(symbol-overlay-face-6 ((t (:background "turquoise1" :foreground "#282c34"))))
 '(symbol-overlay-face-7 ((t (:background "honeydew" :foreground "#282c34"))))
 '(symbol-overlay-face-8 ((t (:background "VioletRed1" :foreground "#282c34")))))
